name: 錯誤回報
description: 用於回報已知且可重現的軟體問題。
body:
  - type: markdown
    attributes:
      value: |
        錯誤回報僅應用於回報軟體運作方式的問題。若需要安裝方面的協助，或是相依套件的除錯協助，請使用我們的 [Discord 伺服器](https://pterodactyl.tw/discord)。

  - type: textarea
    attributes:
      label: 目前行為
      description: 請清楚簡潔地描述此問題。
    validations:
      required: true

  - type: textarea
    attributes:
      label: 預期行為
      description: 請描述你原本預期會發生的情況。
    validations:
      required: true

  - type: textarea
    attributes:
      label: 重現步驟
      description: 請盡可能詳細地提供重現步驟，若未提供步驟，此 issue 將會被關閉。
    validations:
      required: true

  - type: input
    id: panel-version
    attributes:
      label: Panel 版本
      description: 你的 Panel 版本號（latest 不是有效的版本號）
      placeholder: 1.4.0
    validations:
      required: true

  - type: input
    id: wings-version
    attributes:
      label: Wings 版本
      description: 你的 Wings 版本號（latest 不是有效的版本號）
      placeholder: 1.4.2
    validations:
      required: true

  - type: input
    id: egg-details
    attributes:
      label: 受影響的遊戲及／或 Egg
      description: 請註明你遇到此問題時所使用的特定遊戲或 Egg。
      placeholder: Minecraft (Paper), Minecraft (Forge)

  - type: input
    id: docker-image
    attributes:
      label: Docker 映像檔
      description: 你為上述遊戲所使用的特定 Docker 映像檔。
      placeholder: ghcr.io/pterodactyl/yolks:java_17

  - type: textarea
    id: panel-logs
    attributes:
      label: 錯誤日誌
      description: |
        請執行以下指令，收集你系統上的日誌。

        Wings：`sudo wings diagnostics`
        Panel：`tail -n 150 /var/www/pterodactyl/storage/logs/laravel-$(date +%F).log | nc pteropaste.com 99`
      placeholder: "https://pteropaste.com/a1h6z"
      render: bash
    validations:
      required: false

  - type: checkboxes
    attributes:
      label: 是否已有相同的 issue？
      description: 請先[搜尋這裡](https://github.com/Pterodactyl-TW/panel/issues) 確認是否已有相同問題的 issue。
      options:
        - label: 我在開立此 issue 前已搜尋過現有的 issue。我理解若未提供足夠資訊，維護者可能會不加說明直接關閉此 issue。
          required: true
