name: 已預先討論並核准的主題
description: 用於已在 GitHub Discussions 討論區事先討論並核准的主題。
body:
  - type: markdown
    attributes:
      value: |
        **請勿**在未經維護者事先核准、且未有對應討論串的情況下，開立新的功能請求 issue。開立此功能請求 issue 時，你**必須**附上對應的討論串連結，否則將不予進一步考慮並直接關閉。
  - type: textarea
    attributes:
      label: 功能請求內容
  - type: input
    attributes:
      label: GitHub Discussion 連結
      description: 該功能先前經過討論並核准的 GitHub Discussions 討論串連結。
    validations:
      required: true
